<?xml version="1.0"?>
<robot name="ddrive" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find diff_drive)/urdf/ddrive.gazebo.xacro"/>

  <xacro:property name="ddrive" value="$(find diff_drive)/config/ddrive.yaml"/>
  <xacro:property name="dictionary" value="${load_yaml(ddrive)}"/>
  <xacro:property name="box_L" value="${dictionary['box_L']}"/>
  <xacro:property name="box_W" value="${dictionary['box_W']}"/>   
  <xacro:property name="box_H" value="${dictionary['box_H']}"/>   
  <xacro:property name="box_mass" value="${dictionary['box_mass']}"/> 
  <xacro:property name="wheel_scale" value="${dictionary['wheel_scale']}"/> 
  <xacro:property name="caster_radius" value="${dictionary['caster_radius']}"/> 
  <xacro:property name="caster_mass" value="${dictionary['caster_mass']}"/> 

  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="light_black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_L} ${box_W} ${box_H}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_L} ${box_W} ${box_H}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${box_mass}"/>
      <inertia ixx="${box_mass*(box_W**2+box_H**2)/12}" ixy="0.0" ixz="0.0"
               iyy="${box_mass*(box_L**2+box_H**2)/12}" iyz="0.0"
               izz="${box_mass*(box_L**2+box_W**2)/12}"/>
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="${-3*box_L/8} ${box_W/2 + 0.080} 0.0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://diff_drive/meshes/wheels/left_tire.stl" scale="${wheel_scale*0.001} ${wheel_scale*0.001} ${wheel_scale*0.001}"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_scale*0.018}" radius="${wheel_scale*0.033}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_scale*2.8498940e-02}" />
      <inertia ixx="${(wheel_scale**3)*1.1175580e-05}" ixy="${(wheel_scale**3)*-4.2369783e-11}" ixz="${(wheel_scale**3)*-5.9381719e-09}"
               iyy="${(wheel_scale**3)*1.1192413e-05}" iyz="${(wheel_scale**3)*-1.4400107e-11}"
               izz="${(wheel_scale**3)*2.0712558e-05}" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="${-3*box_L/8} ${-box_W/2 - 0.080} 0.0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://diff_drive/meshes/wheels/right_tire.stl" scale="${wheel_scale*0.001} ${wheel_scale*0.001} ${wheel_scale*0.001}"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_scale*0.018}" radius="${wheel_scale*0.033}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_scale*2.8498940e-02}" />
      <inertia ixx="${(wheel_scale**3)*1.1175580e-05}" ixy="${(wheel_scale**3)*-4.2369783e-11}" ixz="${(wheel_scale**3)*-5.9381719e-09}"
               iyy="${(wheel_scale**3)*1.1192413e-05}" iyz="${(wheel_scale**3)*-1.4400107e-11}"
               izz="${(wheel_scale**3)*2.0712558e-05}" />
      </inertial>
  </link>

  <joint name="caster_bottom_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_bottom_back_link"/>
    <origin xyz="${3*box_L/7} 0 ${-box_H/2 - 0.026}" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_bottom_back_link">
    <visual>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.03"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${caster_mass}" />
      <inertia ixx="${(2/5)*caster_mass*caster_radius**2}" ixy="0.0" ixz="0.0"
               iyy="${(2/5)*caster_mass*caster_radius**2}" iyz="0.0"
               izz="${(2/5)*caster_mass*caster_radius**2}" />
    </inertial>
  </link>

  <joint name="caster_top_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_top_back_link"/>
    <origin xyz="${3*box_L/7} 0 ${box_H/2 + 0.026}" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_top_back_link">
    <visual>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.03"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${caster_mass}" />
      <inertia ixx="${(2/5)*caster_mass*caster_radius**2}" ixy="0.0" ixz="0.0"
               iyy="${(2/5)*caster_mass*caster_radius**2}" iyz="0.0"
               izz="${(2/5)*caster_mass*caster_radius**2}" />
    </inertial>
  </link>

</robot>
